model_config:
  model_name: gpt
  PARAMS: 19M
  patch_size: 40
  d_model: 512
  n_heads: 8
  n_layers: 6
  dropout: 0.1
  max_len: 2400
  loss: mse+laplace
  with_conv: false
  out_dim_override: null
  output_size: 2
  out_classes: 2
  apply_mask: false
train_config:
  epochs: 100
  batch_size: 32
  lr_max: 0.0001
  weight_decay: 0.01
  optimizer: Adam
  scheduler: cosine
  save_freq: 10
  num_workers: 4
