model_config:
  base_filters: 32
  kernel_size: 3
  stride: 2
  groups: 1
  n_block: 18
  n_classes: 512
  n_experts: 3
  
  output_size: 1
  dropout: 0.2
  
  model_path: "papagei-foundation-model/weights/papagei_s.pt"
  
  freeze_backbone: false
  
  patch_size: 40
  n_patches: 30

train_config:
  epochs: 50
  batch_size: 32
  lr_max: 0.001
  optimizer: "AdamW"
  weight_decay: 0.01
  scheduler: "cosine"
  
  patience: 10
  min_delta: 0.001 