distillation:
  alpha: 0.5
  beta: 0.1
  gamma: 0
  temperature: 2.0
  
  use_feature_distill: true
  feature_loss_weight: 1.0
  
  use_patch_feature_distill: true
  patch_feature_loss_weight: 1.0
  patch_distill_mode: 'contrastive'
  contrastive_temperature: auto
  
  use_patch_distance_distill: true
  patch_distance_loss_weight: 1.0
  
  tie_feature_and_patch: true

train_config:
  epochs: 120
  batch_size: 64
  lr_init: 1e-5
  lr_max: 1e-3
  lr_final: 1e-6
  lr_schedule_ratio: 1
  lr_warm_up: 0.25
  optimizer: "AdamW"
  weight_decay: 0.00001
  
  save_freq: 10
  
  early_stop_patience: 20
  early_stop_min_delta: 1e-6 